# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-01-03 20:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdog',
            name='dog',
        ),
        migrations.AddField(
            model_name='userdog',
            name='dog',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='users_dog', to='pugorugh.Dog'),
        ),
        migrations.AlterField(
            model_name='userdog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
