# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-01-03 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0002_auto_20180103_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdog',
            name='dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_dog', to='pugorugh.Dog'),
        ),
    ]
