# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-01-07 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0004_auto_20180106_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userdog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
