# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-01-20 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0008_auto_20180118_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdog',
            name='status',
            field=models.CharField(choices=[('l', 'Liked'), ('d', 'disliked'), ('U', 'undicided')], default='U', max_length=10),
        ),
    ]
