# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-01-25 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0009_auto_20180120_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='age',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='age',
            field=models.IntegerField(default=12),
        ),
    ]
